### ISSUE TITLE
Create a Maintainers Committee discussion category

### ISSUE THREAD

**Issue by Perksey** [dotnet-foundation/wg-maintainers#10]
In the [discussions](https://github.com/dotnet-foundation/Home/discussions), each committee seems to have its own category for dumping things like meeting notes, general discussion, or whatever else.

One of these should probably be created for the maintainers committee.

**Comment by devlead** [comment]
We will need to investigate, GitHub seems to not allow more than 10 categories per repository.

**Comment by Perksey** [comment]
Yeah I think it'd make sense to have per-committee discussions anyway, there's a lot of general chatter on the home repo (which I guess is what it's for) whereas committee discussions are (hopefully) a lot more focused.

**Comment by devlead** [comment]
There's now a maintainers category 👍
https://github.com/dotnet-foundation/Home/discussions/categories/maintainers-committee
