### ISSUE TITLE
Membership Application

### ISSUE THREAD

**Issue by tannergooding** [dotnet-foundation/wg-maintainers#11]
## Name:
Tanner Gooding

## Projects:
* microsoft/ClangSharp (applied for transfer to .NET Foundation)
* microsoft/LLVMSharp (applied for transfer to .NET Foundation)
* dotnet/runtime (part of job at Microsoft)
* terrafx/* (independent .NET OSS project)

Part of the projects committee.
Admin on the C# Community Discord.
Participate in various OSS design discussions for various .NET OSS repos

**Comment by devlead** [comment]
Welcome @tannergooding   👋 An invite is on its way to you.

**Comment by tannergooding** [comment]
@devlead, should I have gotten an invite to the slack as well? Looks like its not one of the available workspaces for me.

**Comment by devlead** [comment]
Invite resent to the email in your gh profile

**Comment by tannergooding** [comment]
Thanks! Received it this time.

**Comment by CalvinAllen** [comment]
I've never received an invite to the slack either, though, I'm not sure I have access to the slack team in the first place?

**Comment by devlead** [comment]
@CalvinAllen invite resent

**Comment by CalvinAllen** [comment]
@devlead Got it, thanks!

**Comment by Turnerj** [comment]
Same as @CalvinAllen , I didn't get a Slack invite. Could you send one through?

**Comment by rprouse** [comment]
@Turnerj go to https://join.slack.com/t/netfoundation/shared_invite/zt-c7np4gr7-rN5cjBt4iNFOgUE9seOfzA to sign up then join #maintainers-committee
