### ISSUE TITLE
Membership Application

### ISSUE THREAD

**Issue by Turnerj** [dotnet-foundation/wg-maintainers#13]
## Name:
James Turner

## Projects:
[MongoFramework](https://github.com/TurnerSoftware/MongoFramework), [Cache Tower](https://github.com/TurnerSoftware/CacheTower), [Infinity Crawler](https://github.com/TurnerSoftware/InfinityCrawler), [Sitemap Tools](https://github.com/TurnerSoftware/SitemapTools), [Robots Exclusion Tools](https://github.com/TurnerSoftware/RobotsExclusionTools), [Build Versioning](https://github.com/TurnerSoftware/BuildVersioning), [Schema.NET](https://github.com/RehanSaeed/Schema.NET) and [Quickenshtein](https://github.com/Turnerj/Quickenshtein). I have a few more but those are definitely my main ones currently. That said, none are currently part of the .NET Foundation. I really just want to make the .NET OSS ecosystem the best it can be and help shape the foundation to support it.

**Comment by devlead** [comment]
Welcome @tannergooding   👋 An invite is on its way to you.
