### ISSUE TITLE
Membership

### ISSUE THREAD

**Issue by valadas** [dotnet-foundation/wg-maintainers#17]
## Name:
Daniel Valadas

## Projects:
https://github.com/dnnsoftware/Dnn.Platform
Most projects under https://github.com/dnncommunity
https://github.com/eraware/Eraware.MinimalSkin
https://github.com/valadas/gh-action-template
https://github.com/valadas/Eraware_Dnn_Templates
https://github.com/nvisionative/nvQuickSite

I am willing to help where I can, nice to see some movement on this subject 😄

**Comment by rprouse** [comment]
I've added you to the repo. Please join slack and the #maintainers-committee at https://join.slack.com/t/netfoundation/shared_invite/zt-c7np4gr7-rN5cjBt4iNFOgUE9seOfzA

Welcome aboard.
