### ISSUE TITLE
Membership

### ISSUE THREAD

**Issue by aritchie** [dotnet-foundation/wg-maintainers#18]
## Name:
Allan Ritchie

## Projects:
https://github.com/shinyorg
https://github.com/aritchie
https://github.com/shinyorg/shiny
https://github.com/aritchie/userdialogs
https://github.com/aritchie/bluetoothle

**Comment by rprouse** [comment]
I've added you to the repo. Please join slack and the #maintainers-committee at https://join.slack.com/t/netfoundation/shared_invite/zt-c7np4gr7-rN5cjBt4iNFOgUE9seOfzA

Welcome aboard.
