### ISSUE TITLE
Membership

### ISSUE THREAD

**Issue by JamesNK** [dotnet-foundation/wg-maintainers#20]
## Name:
James Newton-King

## Projects:
* https://github.com/jamesnk/newtonsoft.json
* https://github.com/dotnet/aspnetcore
* https://github.com/grpc/grpc-dotnet (note: not in .NET Foundation)

**Comment by devlead** [comment]
@JamesNK you're now added as an member, and an invite to the .NET Foundation slack on its way to you.
