### ISSUE TITLE
I'd like to join the committee

### ISSUE THREAD

**Issue by tonyqus** [dotnet-foundation/wg-maintainers#21]
Hi Committee,

This is Tony Qu from Shanghai, China. I'm not exactly sure what's the qualification of joining this committee. Do you have perferred timezone or other experience. Let me know.

I'm reading your updates about this committe. Looks I'm also looking for methods of collecting concerns from .NET projects and see how can help them grow and marketting.  In other words, we are on the same page.

**Comment by rprouse** [comment]
I've added you to the repo. Please join slack and the #maintainers-committee at https://join.slack.com/t/netfoundation/shared_invite/zt-c7np4gr7-rN5cjBt4iNFOgUE9seOfzA

Welcome aboard.

**Comment by rprouse** [comment]
We're going to meet at 21:00 UTC on Wed. If that time doesn't work for you, we are also going to try a smaller meeting on Thursday. See Slack for the discussion.
