### ISSUE TITLE
Application

### ISSUE THREAD

**Issue by matkoch** [dotnet-foundation/wg-maintainers#24]
## Name:
Matthias Koch

## Projects:
https://github.com/nuke-build/nuke

Would be great to join.

**Comment by rprouse** [comment]
I've added you to this repo. Short notice, but the first meeting is at 14:00 EST, in two hours, https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZDljNDcxZjAtY2FkYi00ZTVmLWIzNjktMmVjMzZlYzUxYzJh%40thread.v2/0?context=%7b%22Tid%22%3a%2262f8c8c7-a85b-41d1-ba6b-743495fb8a48%22%2c%22Oid%22%3a%2223d27343-1f69-4338-90ca-b310792a3e5d%22%7d

You should also join the Foundation on Slack then join #maintainers-committee, https://join.slack.com/t/netfoundation/shared_invite/zt-c7np4gr7-rN5cjBt4iNFOgUE9seOfzA
