### ISSUE TITLE
Interest in joining maintainers WG

### ISSUE THREAD

**Issue by SeanKilleen** [dotnet-foundation/wg-maintainers#28]
## Name:
Sean Killeen

## Projects:
I currently maintain the [NUnit docs](https://github.com/nunit/docs) and have contributed to Octokit.NET, Akka.NET, and others as I'm able. I have some ideas that I think may be impactful and so I'd appreciate the opportunity to join, listen for a while, and lend a hand as I'm able.

**Comment by devlead** [comment]
Welcome, @SeanKilleen an invite has been sent to the #maintainers-committee Slack and as a collaborator on this repo.
