### ISSUE TITLE
Membership - Aaron LaBeau

### ISSUE THREAD

**Issue by biozal** [dotnet-foundation/wg-maintainers#31]
## Name:
Aaron LaBeau

## Projects:
None

**Comment by rprouse** [comment]
Welcome. I've added you to this repo. If you'd like your name listed in the Readme.md, please submit a PR. I'd also ask that you join the Slack channel @maintainers-committee, https://join.slack.com/t/netfoundation/shared_invite/zt-c7np4gr7-rN5cjBt4iNFOgUE9seOfzA
