### ISSUE TITLE
Membership - Alper Ebicoglu 

### ISSUE THREAD

**Issue by ebicoglu** [dotnet-foundation/wg-maintainers#32]
## Name:
Alper Ebicoglu

## Projects:
Maintainer and one of the repo owners of the ABP Framework
https://github.com/abpframework/abp

Also maintainer and one of the main contacts of the ASP.NET Boilerplate framework, check out https://dotnetfoundation.org/projects/aspnetboilerplate

_Projects that you maintain or contribute to. You do not have to be a project maintainer or contributor, if you have ideas or want to help, you are welcome._

**Comment by rprouse** [comment]
Welcome. I've added you to this repo. If you'd like your name listed in the Readme.md, please submit a PR. I'd also added you to the Slack channel #maintainers-committee
