### ISSUE TITLE
Membership - Furkan GUNGOR

### ISSUE THREAD

**Issue by furkandeveloper** [dotnet-foundation/wg-maintainers#33]
## Name:
[Furkan GUNGOR](https://github.com/furkandeveloper)

### Easy Repository
This repo, provides query profiler for .Net 
[Easy Profiler](https://github.com/furkandeveloper/EasyProfiler)

***

### Easy CronJob
This repository provides easy cron job to your application on IHostedService. 
[EasyCronJob](https://github.com/furkandeveloper/EasyCronJob)

***

### Easy Cache
This library contains more than one cache provider for dotnet. 
[EasyCache](https://github.com/furkandeveloper/EasyCache)

***

### Iron Hook
This repository provides easily management hook operations for dotnet application. 
[Iron Hook](https://github.com/FowApps/IronHook)

***

### Easy Permission Management
This repo provides easily permission management on your aspnetcore project
[Easy Permission Management](https://github.com/furkandeveloper/EasyPermissionManagement)

***

### Easy Repository EF Core
This repo provides implementation generic repository pattern on Entity Framework Core 
[Easy Repositoy EF Core](https://github.com/furkandeveloper/EasyRepository.EFCore)

_Projects that you maintain or contribute to. You do not have to be a project maintainer or contributor, if you have ideas or want to help, you are welcome._

**Comment by rprouse** [comment]
Welcome. I've added you to this repo. If you'd like your name listed in the Readme.md, please submit a PR. I'd also ask that you join the Slack channel @maintainers-committee, https://join.slack.com/t/netfoundation/shared_invite/zt-c7np4gr7-rN5cjBt4iNFOgUE9seOfzA
