### ISSUE TITLE
Membership - Alireza Sabouri

### ISSUE THREAD

**Issue by alirezanet** [dotnet-foundation/wg-maintainers#34]
## Name:
AliReZa Sabouri

## Projects:
Just want to help but I also have a few projects (Gridify - Husky.Net ...)

**Comment by rprouse** [comment]
Welcome. I've added you to this repo. If you'd like your name listed in the Readme.md, please submit a PR. I'd also ask that you join the Slack channel @maintainers-committee, https://join.slack.com/t/netfoundation/shared_invite/zt-c7np4gr7-rN5cjBt4iNFOgUE9seOfzA
