### ISSUE TITLE
Membership - Robin Krom

### ISSUE THREAD

**Issue by Lakritzator** [dotnet-foundation/wg-maintainers#35]
## Name:
Robin Krom

## Projects:
Here are some projects I am the maintainer for, all are made with .NET
- [Greenshot](https://getgreenshot.org) a screenshot tool for Windows
- [Dapplo.Windows](https://github.com/dapplo/Dapplo.Windows) more modern win32 APIs, e.g. use reactive to process clipboard changes, key/mouse raw input etc.
- [Dapplo.HttpExtensions](https://github.com/dapplo/Dapplo.HttpExtensions) Another project to simplify HTTP client usage
- [Dapplo.Jira](https://github.com/dapplo/Dapplo.Jira) A Jira client
- [Dapplo.Confluence](https://github.com/dapplo/Dapplo.Confluence) A Confluence client
- [Dapplo.Microsoft.Extensions.Hosting](https://github.com/dapplo/Dapplo.Microsoft.Extensions.Hosting) A generic host for WPF, WinForms and beta for WinUI.

Here is one I contribute often:
- [WPF Notify Icon](https://github.com/hardcodet/wpf-notifyicon) A notifyIcon for WPF from Hardcoded

**Comment by rprouse** [comment]
Welcome. I've added you to this repo. If you'd like your name listed in the Readme.md, please submit a PR. I'd also ask that you join the Slack channel @maintainers-committee, https://join.slack.com/t/netfoundation/shared_invite/zt-c7np4gr7-rN5cjBt4iNFOgUE9seOfzA
