### ISSUE TITLE
Membership - Enis Necipoglu

### ISSUE THREAD

**Issue by enisn** [dotnet-foundation/wg-maintainers#41]
## Name:
Enis Necipoglu

## Projects:
_Projects that you maintain or contribute to. You do not have to be a project maintainer or contributor, if you have ideas or want to help, you are welcome._

- I maintain & contribute to [abpframework](https://github.com/abpframework/abp)

- I am owner & maintainer of following repositories:
  - [Xamarin.Forms.InputKit](https://github.com/enisn/Xamarin.Forms.InputKit)
  - [AutoFilterer](https://github.com/enisn/AutoFilterer)
  - [DotNurseInjector](https://github.com/enisn/DotNurseInjector)

**Comment by rprouse** [comment]
Welcome. I've added you to this repo. If you'd like your name listed in the `Readme.md`, please submit a PR. I'd also ask that you join the Slack channel #maintainers-committee, https://join.slack.com/t/netfoundation/shared_invite/zt-c7np4gr7-rN5cjBt4iNFOgUE9seOfzA
