### ISSUE TITLE
Agenda for 2022-01-12 Members Committee Meeting

### ISSUE THREAD

**Issue by rprouse** [dotnet-foundation/wg-maintainers#50]
Agenda for tomorrow's meeting at 17:00 EST

- Review previous [meetings minutes](https://github.com/dotnet-foundation/wg-maintainers/blob/main/Meetings/2021-12-08-meeting-minutes.md)
- Probationary committee membership, see #48 
- Alternate meeting times for people in other time zones
- Proposal by @SeanKilleen about maintainer satisfaction
- Other business

If anyone has additional items for the agenda, please comment below. See you tomorrow.

**Comment by tonyqus** [comment]
Shall we discuss what's the current benefits of joining DNF for projects? In my view,  this is the core part DNF should improve. Some projects leaving DNF is because they don't see benefits.

**Comment by Lakritzator** [comment]
FYI: I will unfortunately not be able to attend today, my first "appearance" will be next week.
My kid (5yo) kept me awake last night, and having a meeting at 23:00 in the evening, I'm at CET, well 😴 
Normally not a problem, but my kid picked a bad night.

Sorry, but hope you have a fruitful meeting!
