### ISSUE TITLE
Agenda for 2022-02-16 Meeting (Note the change of date)

### ISSUE THREAD

**Issue by rprouse** [dotnet-foundation/wg-maintainers#51]
**This month's meeting is being moved to 16 February at 16:00 EST, 21:00 UTC.**

**Comment by devlead** [comment]
Agenda for Agenda today's meeting at 16:00 EST, 21:00 UTC

- Review previous [meetings minutes](https://github.com/dotnet-foundation/wg-maintainers/blob/main/Meetings/2022-01-12-meeting-minutes.md)
- Leaving the .NET Foundation process
  - Walkthrough the latest draft (posted on [discussions](https://github.com/dotnet-foundation/Home/discussions/68#discussioncomment-2168432)).
  - Feedback / Q & A
  - Road map
- Other business

Microsoft Teams Link for today's Maintainers meeting at 16:00 EST, 21:00 UTC.
[Click here to join the meeting](https://teams.microsoft.com/l/meetup-join/19%3ameeting_OWU3OWVmMjYtYzZjOS00ODhlLWI3NDYtOTdiNmQ1YTgxYTA0%40thread.v2/0?context=%7b%22Tid%22%3a%2262f8c8c7-a85b-41d1-ba6b-743495fb8a48%22%2c%22Oid%22%3a%2223d27343-1f69-4338-90ca-b310792a3e5d%22%7d)

**Comment by rprouse** [comment]
And if @SimonCropp is available, review the progress of his survey.

**Comment by devlead** [comment]
> And if @SimonCropp is available, review the progress of his survey.

That would be @SeanKilleen

**Comment by glennawatson** [comment]
If we can also bring up the signing owner lockout on nuget as well thankyou

**Comment by michael-hawker** [comment]
Would love to talk about addressing centralizing and providing guidance to project maintainers for common questions/issues that arise and how to address them, [from this thread here](https://github.com/dotnet-foundation/Home/discussions/61).

**Comment by michael-hawker** [comment]
Still planning for March meeting on the 9th? Don't see a new issue for it yet.

**Comment by rprouse** [comment]
@michael-hawker, yes, working on the meeting notes now, then I'll create an issue for the next meeting.
