### ISSUE TITLE
Agenda item: dnfadmin uses including CoC bans

### ISSUE THREAD

**Issue by glennawatson** [dotnet-foundation/wg-maintainers#55]
At the moment there seems to be confusion about allowed uses for the dnfadmin admin account on member projects 

The agenda item would discuss
* Current uses of the dnfadmin account by the foundation such as the ban bot
* Maintainers expectation of uses going forward 

Some of these usages may be accomplished by using opt in GitHub actions. For example @terrajobst has indicated the ban bot could be moved to a GitHub action that member projects can opt into. This could also offer configured control of what type of bans they would want to opt into.

**Comment by Perksey** [comment]
It's also worth noting the enforcement services only cover GitHub today. If the ban bot was available as a GitHub Action, this could open up the opportunity to expand to other platforms as well (e.g. I was planning at some point to write a Discord bot for this)

**Comment by glennawatson** [comment]
> It's also worth noting the enforcement services only cover GitHub today. If the ban bot was available as a GitHub Action, this could open up the opportunity to expand to other platforms as well (e.g. I was planning at some point to write a Discord bot for CoC enforcement)

Yeah which is also another topic around privacy and what data member projects should be exposed to, and what that data is allowed to be used for and such. 

I know Australia has strict privacy laws for example where you have to define that type of uses.

**Comment by glennawatson** [comment]
Have had it confirmed by @BillWagner that the only current uses of the dnfadmin account are 

* Ban CoC enforcer not
* Emergency use for project continuity

**Comment by glennawatson** [comment]
Btw @Perksey good suggestion and definitely hope my reply didn't seem to stomp on it. I suspect common sense rules with my suggestion. Like it has to be only for the projects chat channels or something. 

Might be worth getting the GitHub action support common platforms like discord, slack and teams maybe.

**Comment by JeremySkinner** [comment]
I think it could also be worth getting some clarification on what access dnfadmin needs in order to allow the CLA process to work. 

IIRC setting up the CLA bot required giving admin access at the organisation level, although I removed the account's admin access from my org after the GH enterprise issue, and CLAs still seem to work OK (it still has access at the repo level) so I think it'd be good to understand what's actually needed for the CLA bot to work.
