### ISSUE TITLE
Agenda for 2022-03-09 Meeting

### ISSUE THREAD

**Issue by rprouse** [dotnet-foundation/wg-maintainers#59]
## Meeting Link

Wednesday 9 March 2022 at 16:00 EST. [Join Teams meeting](https://teams.microsoft.com/dl/launcher/launcher.html?url=%2F_%23%2Fl%2Fmeetup-join%2F19%3Ameeting_OWU3OWVmMjYtYzZjOS00ODhlLWI3NDYtOTdiNmQ1YTgxYTA0%40thread.v2%2F0%3Fcontext%3D%257b%2522Tid%2522%253a%252262f8c8c7-a85b-41d1-ba6b-743495fb8a48%2522%252c%2522Oid%2522%253a%252223d27343-1f69-4338-90ca-b310792a3e5d%2522%257d%26anon%3Dtrue&type=meetup-join&deeplinkId=b10215ba-0741-4ba5-9712-b01692d19226&directDl=true&msLaunch=true&enableMobilePage=true&suppressPrompt=true)

## Agenda

- Review previous [meeting minutes](https://github.com/dotnet-foundation/wg-maintainers/blob/main/Meetings/2022-02-16-meeting-minutes.md)
- Briefly discuss ()[https://github.com/dotnet-foundation/wg-maintainers/issues/48]
- Talk about how we can provide better guidance to maintainers from this thread as well: [Centralised information for .NET Foundation operation](https://github.com/dotnet-foundation/Home/discussions/61)
- Discuss #55 and #56 
- Other business

**Comment by oskardudycz** [comment]
@rprouse, could you post previous meetings notes? They're not available. Will the procedure of leaving DNF be discussed?

**Comment by nils-a** [comment]
@oskardudycz have a look at https://github.com/dotnet-foundation/wg-maintainers/pull/58

**Comment by oskardudycz** [comment]
@nils-a, thank you. I missed that 👍 

So am I correct to think that procedure will be discussed?

**Comment by rprouse** [comment]
Meeting notes for every meeting are already posted here. We weren't planning on discussing leaving the foundation again, we've already discussed it in two meetings and it is going back to the Board to finalize the process.

**Comment by oskardudycz** [comment]
What's the exact plan then? I've read the docs but it's unclear for me what's left and what's the timeline.

Could you (or someone else from the board) post an update with a clear statement in the dedicated GH discussion that we have? https://github.com/dotnet-foundation/Home/discussions/68#discussioncomment-2234319

**Comment by oskardudycz** [comment]
@rprouse, @devlead, is there a summary from the Board meeting? I'd like to know if the Off-boarding procedure will be discussed today or all was set up.

**Comment by Lakritzator** [comment]
I'm curious if I can do anything to help @SeanKilleen with his [survey](https://dotnetfoundation.us12.list-manage.com/track/click?u=9d9421a5cbd70d03dc69dc918&id=0cf1da5eca&e=f3bb193978), if it "just" needs time that is okay too.

**Comment by SeanKilleen** [comment]
@Lakritzator 

> I'm curious if I can do anything to help @SeanKilleen with his [survey](https://dotnetfoundation.us12.list-manage.com/track/click?u=9d9421a5cbd70d03dc69dc918&id=0cf1da5eca&e=f3bb193978), if it "just" needs time that is okay too.

Thanks for asking! When I previously brought this up in the meeting, there didn't seem to be any takers for specific support beyond amplification, and it didn't seem that the Foundation wanted to do this survey under their umbrella, so I ran it on my own. The survey did not receive many results (35), and I still have a task to analyze and write up the answers which I hope to do any day.

**Comment by nicoleabuhakmeh** [comment]
Hi @SeanKilleen  - The board didn't meet last month, that pushed the newsletter out to this coming Monday (14th). Any chance you can hold off on analyzing until the next week?

**Comment by SeanKilleen** [comment]
@nicoleabuhakmeh sure thing -- Thanks for the heads up!

**Comment by rprouse** [comment]
@oskardudycz , the board has approved the offboarding process, we have met with the lawyers and will begin offboarding the projects that have requested to leave very soon.

**Comment by oskardudycz** [comment]
@rprouse, thabk you for the information. Great that we’re getting closer. I hope that list includes us; if not, I’d be grateful for what steps I shall take to be on it.
