### ISSUE TITLE
Membership: Halil İbrahim Kalkan

### ISSUE THREAD

**Issue by hikalkan** [dotnet-foundation/wg-maintainers#60]
## Name:

Halil İbrahim Kalkan

## Projects:

* https://github.com/abpframework/abp (I am the lead contributor of the project).
* https://github.com/aspnetboilerplate/aspnetboilerplate (Old, but still active, generation of the same project. This is a .NET Foundation project).

**Comment by tonyqus** [comment]
ABP.... It's nice to see you here. Welcome!

**Comment by hikalkan** [comment]
Thanks @tonyqus :)
@rprouse I will attend to the meeting. See you.
