### ISSUE TITLE
2022-05-11 Meeting Agenda

### ISSUE THREAD

**Issue by devlead** [dotnet-foundation/wg-maintainers#68]
Sorry a bit late with the issue.

Time: 21:00 UTC / 17:00 EST / 14:00 PST

[Click here to join the meeting](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZGU5NWZjYTItOTFiZi00OWQyLWExYTItMWQ4ZWM0YzhlZTA4%40thread.v2/0?context=%7b%22Tid%22%3a%22f0bdbbf2-cd76-4967-8c4c-50a802746912%22%2c%22Oid%22%3a%2233e33123-f641-455f-8467-58a715c2da80%22%7d)

## Agenda

No items have been brought to our attention, possible talking points.

- .NET Foundation Website?
- Other Business

Please add additional agenda items in the comments below.

**Comment by rprouse** [comment]
## Meeting Notes

- Set up a poll in the Slack channel for time alternatives for the meeting. Should we alternate times every other month?
- Mattias and Rob to attend project committee to define boundaries between the committees
- Projects are starting to offboard. Martin is complete, Prism is started. There might be one other project in the pipeline.
- Sponsorship benefits are ongoing and will be released soon.
- Projects benefits. What benefits can projects use? It would be good if project maintainers could come up with support they need.
    - Trademark search?
    - Azure credits
    - Technical writers to help with the websites
    - A legal FAQ for maintainers, our agreements, infringements, etc.
- Sitefinity and American Eagle website transition is signed
- Are there any plans for a maintainer's wiki?
- New membership website is in the works
- How can we open up membership more widely to students and non-technical people
    - We've had designers and writers help out with projects
    - Having an active GitHub account may not be a good indicator
    - If we have voting members we need to verify they are a real person
    - How do other Foundations deal with this
    - Apache only accepts nominated members
    - Other groups have student and other classes of members
    - Can a member projects be sponsors? Needs to scale and be simple.
    - Automated ways like verifying PRs, issues, nuget packages, etc.

## Action Items
- Set up a poll in the Slack channel for time alternatives for the meeting.
- Feed the membership ideas back to to the membership committee

**Comment by glennawatson** [comment]
With the automated way of checking members, be useful to see the full applicant details including their response to questions and see something like "ticks/crosses" against the automated metrics. That way for the easy cases a membership committee can just hit the "Approve" button quickly. It won't cover more edge cases but will simplify the easier cases where the applicant has done a lot of open source development.
