### ISSUE TITLE
Meeting Agenda - 17 August 2022 19:00 UTC (15:00 ET)

### ISSUE THREAD

**Issue by rprouse** [dotnet-foundation/wg-maintainers#73]
Please note, the meeting has been moved to Wednesday 17 August this month and is two hours earlier at 19:00 UTC based on the polls.

[Microsoft Teams Meeting Link](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZGU5NWZjYTItOTFiZi00OWQyLWExYTItMWQ4ZWM0YzhlZTA4%40thread.v2/0?context=%7b%22Tid%22%3a%22f0bdbbf2-cd76-4967-8c4c-50a802746912%22%2c%22Oid%22%3a%2233e33123-f641-455f-8467-58a715c2da80%22%7d)

## Agenda

- Discuss [ImageSharp's licenses change](https://sixlabors.com/posts/license-changes/)
- Other business

**Please add agenda items in comments below**

**Comment by JimBobSquarePants** [comment]
Probably would have been wise to schedule it at a time where the owner of the repository in question would have been able to attend.

**Comment by glennawatson** [comment]
21:00 had the same number of votes as 19:00 and a little more Aussie friendly

Might be worth adopting a alternating time schedule?

**Comment by glennawatson** [comment]
@rprouse has asked me to find a better time that works for you @JimBobSquarePants since he's travelling with limited access to the internet at the moment

21:00 had the same votes in the polls

**Comment by JimBobSquarePants** [comment]
21:00 UTC is 6:00 am AEST. The best times are early to mid morning UTC. For example 10:00 UTC is 19:00 AEST

https://www.timeanddate.com/worldclock/converter.html?iso=20220729T090000&p1=136&p2=240

**Comment by glennawatson** [comment]
21:00 utc is 07:00AEST and I live in the same time zone. UK has daylight savings so different again

**Comment by JimBobSquarePants** [comment]
I'm still not getting up for that. Carry on without me, although I'm disappointed that this is an afterthought.

**Comment by glennawatson** [comment]
What time in the morning AEST works for you and I'll chase around getting availability of people.

**Comment by devlead** [comment]
So the turnout was too low for the topic we were to discuss. We need to find a new time.
