### ISSUE TITLE
Meeting Agenda - 2022-09-14

### ISSUE THREAD

**Issue by rprouse** [dotnet-foundation/wg-maintainers#74]
[Microsoft Teams Meeting Link](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZGU5NWZjYTItOTFiZi00OWQyLWExYTItMWQ4ZWM0YzhlZTA4%40thread.v2/0?context=%7b%22Tid%22%3a%22f0bdbbf2-cd76-4967-8c4c-50a802746912%22%2c%22Oid%22%3a%2233e33123-f641-455f-8467-58a715c2da80%22%7d)

## Agenda

- Discuss [ImageSharp's licenses change](https://sixlabors.com/posts/license-changes/)
- Review project benefits
- How do we balance projects wanting to monetize their projects with the promises of the Foundation
- Is there interest and value in the Project Spotlight?
- Other business

**Please add agenda items in comments below**

**Comment by devlead** [comment]
Doodle so we can see when people can, so we'll find a time that works for most people
https://doodle.com/meeting/participate/id/dN990MLb

**Comment by devlead** [comment]
Top pics from doodle

## Alternative 1

| Time Zone                                   | Time  | Date             |
|---------------------------------------------|-------|------------------|
| PDT/PST, Pacific Daylight Time (US)         | 04:00 | Wed, Sep 14 2022 |
| EDT/EST, Eastern Daylight Time (US)         | 07:00 | Wed, Sep 14 2022 |
| UTC, Coordinated Universal Time             | 11:00 | Wed, Sep 14 2022 |
| BST/GMT, British Summer Time                | 12:00 | Wed, Sep 14 2022 |
| CEST/CET, Central European Summer Time      | 13:00 | Wed, Sep 14 2022 |
| AWST, Australian Western Standard Time      | 19:00 | Wed, Sep 14 2022 |
| AEST/AEDT, Australian Eastern Standard Time | 21:00 | Wed, Sep 14 2022 |

## Alternative 2

| Time Zone                                   | Time  | Date             |
|---------------------------------------------|-------|------------------|
| PDT/PST, Pacific Daylight Time (US)         | 16:00 | Wed, Sep 14 2022 |
| EDT/EST, Eastern Daylight Time (US)         | 19:00 | Wed, Sep 14 2022 |
| UTC, Coordinated Universal Time             | 23:00 | Wed, Sep 14 2022 |
| BST/GMT, British Summer Time                | 00:00 | Thu, Sep 15 2022 |
| CEST/CET, Central European Summer Time      | 01:00 | Thu, Sep 15 2022 |
| AWST, Australian Western Standard Time      | 07:00 | Thu, Sep 15 2022 |
| AEST/AEDT, Australian Eastern Standard Time | 09:00 | Thu, Sep 15 2022 |

**Comment by michael-hawker** [comment]
4AM for Pacific time is too early, so I'd prefer Alternative 2.

Would like to add an agenda item to discuss SPDX as I think that may be being discussed for adoption? So any status update or info would be great.

**Comment by devlead** [comment]
One alternative is that we do both slots to ensure as many as possible can be heard.
I can make myself available for both.

**Comment by Lakritzator** [comment]
Ouch, both are horrible picks for a working father living in Europe (CEST), but I find the topics very important and close to my hearth. I can make alternative 1 possible, but only up to 1 hour.

**Comment by glennawatson** [comment]
Either is good for me.

@devlead are you planning on having doing both meetings on the same day?

**Comment by devlead** [comment]
> Either is good for me.
> 
> @devlead are you planning on having doing both meetings on the same day?

I could do both. @rprouse how does it look for you!

**Comment by rprouse** [comment]
I can do either

**Comment by devlead** [comment]
> Sorry, I meant that I can do both

Excellent, then I think that is settled and we should all help to get as many people as possible aware of that.

**Comment by nicoleabuhakmeh** [comment]
Do we need to have Madison update the meeting invite?  I think the current invite says 3pm Eastern.

**Comment by devlead** [comment]
@nicoleabuhakmeh first one is in 2h, next one is in 14h, so perhaps we could update the current invite for today to the second slot.
Tested [Microsoft Teams Meeting Link](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZGU5NWZjYTItOTFiZi00OWQyLWExYTItMWQ4ZWM0YzhlZTA4%40thread.v2/0?context=%7b%22Tid%22%3a%22f0bdbbf2-cd76-4967-8c4c-50a802746912%22%2c%22Oid%22%3a%2233e33123-f641-455f-8467-58a715c2da80%22%7d) so it works regardless, and pinged people here, on discord, and Slack hopefully they know when it is.

**Comment by valadas** [comment]
I am confused the ics on the root of this repo dates from like april and I don't have this on either slack or discord. Can I get slack/discord invites please.

**Comment by devlead** [comment]
> I am confused the ics on the root of this repo dates from like april and I don't have this on either slack or discord. Can I get slack/discord invites please.

Sure, you can use [this link](https://t.co/PNF2NGZWgR) to join the .NET Foundation discord. There's a [Committees/#maintainers](https://discord.com/channels/966483029830824008/966484217452187658) channel there.

**Comment by valadas** [comment]
> > I am confused the ics on the root of this repo dates from like april and I don't have this on either slack or discord. Can I get slack/discord invites please.
> 
> Sure, you can use [this link](https://t.co/PNF2NGZWgR) to join the .NET Foundation discord. There's a [Committees/#maintainers](https://discord.com/channels/966483029830824008/966484217452187658) channel there.

Thank you! joined...

**Comment by michael-hawker** [comment]
@rprouse is there a meeting this month?
