### ISSUE TITLE
Meeting Agenda - 2022-11-09

### ISSUE THREAD

**Issue by devlead** [dotnet-foundation/wg-maintainers#75]
[Microsoft Teams Meeting Link](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZGU5NWZjYTItOTFiZi00OWQyLWExYTItMWQ4ZWM0YzhlZTA4%40thread.v2/0?context=%7b%22Tid%22%3a%22f0bdbbf2-cd76-4967-8c4c-50a802746912%22%2c%22Oid%22%3a%2233e33123-f641-455f-8467-58a715c2da80%22%7d)

## Agenda

- Security
- CLAs
- Communication
- Other business

**Comment by rprouse** [comment]
#### Attendees
Mattias Karlson
Chris Martinez
Dylan Perks
Rob Prouse
Stacey Ramsey

#### Topics of Discussion
- Discuss security
- Discuss communications channels
- CLA Bot
    - CLA bot is falling apart, projects need to migrate to the new bot
    - New bot has not been installed yet in the Org
    - Previously signed agreements have been transferred
    - https://github.com/dotnet-foundation/.github/tree/main/CLA
    - https://github.com/cake-build/.github/tree/main/policies
    - https://github.com/microsoft/ContributorLicenseAgreement
- Create a newsletter/mailing list for project maintainers
- https://twitter.com/github/status/1590409080178630656?t=Uifwxuk1DymmVsLDsoSUkw&s=19
- The new website is coming soon. The marketing committee would welcome volunteers
- Code signing backing service is changing, should be no change for projects. Old service goes out of support in Q1 2023.
