### ISSUE TITLE
Meeting Agenda - 2022-12-14

### ISSUE THREAD

**Issue by devlead** [dotnet-foundation/wg-maintainers#77]
[Microsoft Teams Meeting Link](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZGU5NWZjYTItOTFiZi00OWQyLWExYTItMWQ4ZWM0YzhlZTA4%40thread.v2/0?context=%7b%22Tid%22%3a%22f0bdbbf2-cd76-4967-8c4c-50a802746912%22%2c%22Oid%22%3a%2233e33123-f641-455f-8467-58a715c2da80%22%7d)

## Agenda

- Update CLA bot
- Update Signing Service
- Other business

**Comment by michael-hawker** [comment]
Is the meeting time still 12PM PT / 3PM ET? Wondering if the calendar item I have is up-to-date.

**Comment by devlead** [comment]
Yes the meeting is in 75 minutes
