### ISSUE TITLE
Membership Application

### ISSUE THREAD

**Issue by CalvinAllen** [dotnet-foundation/wg-maintainers#8]
## Name:
Calvin Allen

## Projects:
I only have some very small projects I maintain, nothing part of the foundation.  I am however extremely interested in helping however I can, and guinenly interested in learning more about OSS projects and their maintainers through this process.

**Comment by rprouse** [comment]
Thanks for stepping up @CalvinAllen, I've added you to this repo. Watch this space 😄 

![](https://media1.giphy.com/media/Ae7SI3LoPYj8Q/giphy.gif)
