### ISSUE TITLE
Meeting Agenda - 2023-01-11 - 20:00 UTC

### ISSUE THREAD

**Issue by devlead** [dotnet-foundation/wg-maintainers#81]
[Microsoft Teams Meeting Link](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZGU5NWZjYTItOTFiZi00OWQyLWExYTItMWQ4ZWM0YzhlZTA4%40thread.v2/0?context=%7b%22Tid%22%3a%22f0bdbbf2-cd76-4967-8c4c-50a802746912%22%2c%22Oid%22%3a%2233e33123-f641-455f-8467-58a715c2da80%22%7d)

## Agenda

- Migrate from LastPass
- Other business

*Please add agenda items in the comments below*

**Comment by tonyqus** [comment]
I'd like to ask where I can input interested topics for next meeting.

**Comment by rprouse** [comment]
Apologies @tonyqus, feel free to post topics in an issue here or in Slack or Discord.
