### ISSUE TITLE
2023-04-12 19:00 UTC Maintainers Meeting Agenda

### ISSUE THREAD

**Issue by rprouse** [dotnet-foundation/wg-maintainers#86]
[Microsoft Teams Meeting Link](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZGU5NWZjYTItOTFiZi00OWQyLWExYTItMWQ4ZWM0YzhlZTA4%40thread.v2/0?context=%7b%22Tid%22%3a%22f0bdbbf2-cd76-4967-8c4c-50a802746912%22%2c%22Oid%22%3a%2233e33123-f641-455f-8467-58a715c2da80%22%7d)

## Agenda

- Review action items
- Other business

*Please add agenda items in the comments below*

**Comment by nicoleabuhakmeh** [comment]
Add a few discussion items from the Maintainer's newsletter: 

- Request from the community to get more maintainers added to projects.  Discussion on maybe matching members to projects for support. How: create an issue here?

- Project Benefits: What are they currently, who is utilizing them, how are they being 'paid for', if/when do they expire? Why: Documentation, we want to update our tracker to make sure we catch any expiring benefits before it happens.  Including Domains, Password safes, Azure/AWS credits, code signing (Microsoft/in-kind sponsorship item), add a long-term check-in plan.

- Define the process/document the ways to ask for support and workflow/Responsible parties; Support@dotnetfoundation.org or an Issue logged in Maintainer's committee -  How else can we handle these items so they don't get missed or forgotten. 

- Discussion around marketing pieces for each project - written by members for the .NET Foundation blog
