### ISSUE TITLE
CLA links are broken and there is no human-readable document available

### ISSUE THREAD

**Issue by jeffhandley** [dotnet-foundation/wg-maintainers#91]
While [updating the dotnet/runtime repo's documentation](https://github.com/dotnet/runtime/pull/86825) to reference the [new CLA bot's `rerun` command](https://github.com/microsoft/ContributorLicenseAgreement/issues/123), I found that our links to the .NET Foundation CLA are broken. I cannot find a URL that shows the foundation’s CLA in human-readable form so that we can show potential contributors what the CLA will be if they submit a pull request.
 
Both the dotnet/runtime repo and https://cla.opensource.microsoft.com/ (which redirects to https://opensource.microsoft.com/cla) link out to https://cla.dotnetfoundation.org/ but that link is defunct, with DNS not resolving the subdomain. I found https://github.com/dotnet-foundation/foundation/blob/master/guidance/net-foundation-contribution-license-agreement.pdf, but it’s an archived project and the document is watermarked as a sample.
 
With the new policy bot, I know that the source of truth for the CLA is the https://github.com/dotnet-foundation/.github/main/CLA/dotnetfoundation.yml file. Is there a PDF or other human-readable, rich-text format copy of the document that we can link out to in the documentation?

Once we have the right link, I will update the dotnet/runtime repo and look for other repos with broken CLA links too. I’m not sure who needs to fix the https://opensource.microsoft.com/cla/ page.

**Comment by captainsafia** [comment]
@jeffhandley A user reported this in ASP.NET Core too: https://github.com/dotnet/aspnetcore/issues/48468

I found references to the defunct link via https://grep.app/search?q=https%3A//cla.dotnetfoundation.org/.

**Comment by jeffhandley** [comment]
Good thinking using grep.app, @captainsafia!

There are also paths under that domain such as `https://cla.dotnetfoundation.org/cake-build/cake` ([link to content](https://github.com/cake-build/cake/blob/b55239f748f921edc303d644839183e9727e00a4/nuspec/NuGet.org.md?plain=1#L22)) that will fail now, but would also no longer have a project-specific page.

With a search for cla.opensource.microsoft.com ([link to search](https://grep.app/search?current=2&q=cla.opensource.microsoft.com)), I noticed some of these similarly going to paths under that domain, such as `https://cla.opensource.microsoft.com/microsoft/winget-pkgs`, but those specific paths just redirect back to the main `https://opensource.microsoft.com/cla/` page now ([link to content](https://github.com/microsoft/winget-cli/blob/b7b2f0e8583e3c522989421b6d439bb1048045b1/.github/PULL_REQUEST_TEMPLATE.md?plain=1#L3)).

A search that doesn't include the https but just has the domain ([link to search](https://grep.app/search?q=cla.dotnetfoundation.org)) also shows a CSS content match ([link to content](https://github.com/StylishThemes/Feature-Override-Styles/blob/79f09a171acaccc577907666d015de41373abd00/github-dark-img-bg-clr.user.css#LL39C218-L39C266)).

**Comment by jeffhandley** [comment]
This issue seems to have been resolved. https://cla.dotnetfoundation.org now responds with the rich-text CLA document.

**Comment by richlander** [comment]
@isaacrlevin fixed it for us. Thanks!
