### ISSUE TITLE
I want to join Membership

### ISSUE THREAD

**Issue by LessIsMoreInSZ** [dotnet-foundation/wg-maintainers#95]
## Name:
my name is Anders.Jiang

## Projects:
l worked C# for four years ,now ,i want to start a opensource project about wpf and webapi.
I mainly do industrial software, and I hope to separate the interface and logic code in industrial software through this project. If possible, I would also like to introduce some 3D elements in the interface section to increase the visibility.
I hope to make some contribution to the development of industrial software,and i want to make some new friends in here.

**Comment by glennawatson** [comment]
https://github.com/dotnet-foundation/projects

The maintainers committee has been combined into the projects committee. Feel free to make a application there.

We discuss maintainer issues along with project submissions as part of the committee and regularly meet on discord.
